trigger:
  branches:
    include:
      - main  # ✅ Runs on every commit to "main"

pool:
  name: Default  # ✅ Uses self-hosted agent (Windows/Linux/Mac)

jobs:
  - job: AlwaysSuccess
    displayName: "Always Succeed Job"
    steps:
      - script: |
          echo "Success!"
          exit /b 0  # ✅ Windows CMD & PowerShell compatible
        displayName: "Force Success"
